# Generated by Django 4.2.7 on 2023-11-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoHogwarts',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoa')),
                ('casa', models.CharField(max_length=50)),
                ('ano', models.PositiveIntegerField()),
                ('varinha', models.CharField(max_length=50)),
            ],
            bases=('pessoa.pessoa', models.Model),
        ),
    ]
