# Generated by Django 4.2.7 on 2023-11-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscolaHogwarts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('alunos', models.ManyToManyField(to='aluno.alunohogwarts')),
                ('funcionarios', models.ManyToManyField(to='funcionario.funcionariohogwarts')),
            ],
        ),
    ]
